import React from 'react';
import { PublisherCoverageGraph } from './PublisherCoverageGraph';

// Circle SVG Progress Bar matching the "AI Reliability Scorecard" design
export function ScorecardCircle({ score }) {
    if (score === null || score === undefined || isNaN(score)) {
        return (
            <div className="flex flex-col items-center p-4 mb-4">
                <div className="w-32 h-32 rounded-full border-4 border-dashed border-white/20 flex flex-col items-center justify-center bg-white/[0.02] mb-3">
                    <span className="text-2xl mb-1 opacity-50"></span>
                    <span className="text-[10px] uppercase font-bold text-gray-400">Pending</span>
                </div>
                <span className="text-[10px] font-bold tracking-widest uppercase text-gray-500">
                    Awaiting Analysis
                </span>
            </div>
        );
    }

    const percentage = Math.round(score * 100);
    const radius = 70;
    const stroke = 12;
    const normalizedRadius = radius - stroke * 2;
    const circumference = normalizedRadius * 2 * Math.PI;
    const strokeDashoffset = circumference - percentage / 100 * circumference;

    const isHigh = percentage >= 70;
    const color = isHigh ? '#ffffff' : '#9ca3af'; // pure white for reliable, gray for medium
    const gradientId = `grad-${percentage}`;

    return (
        <div className="flex flex-col items-center p-4 mb-4 relative">
            {/* Wrapper for SVG and absolute text to ensure perfect centering regardless of labels below */}
            <div className="relative flex items-center justify-center p-2 mb-2">
                <svg
                    height={radius * 2}
                    width={radius * 2}
                    className="transform -rotate-90 drop-shadow-[0_0_15px_rgba(255,255,255,0.1)]"
                >
                    <defs>
                        <linearGradient id={gradientId} x1="0%" y1="0%" x2="100%" y2="0%">
                            <stop offset="0%" stopColor={isHigh ? '#ffffff' : '#9ca3af'} />
                            <stop offset="100%" stopColor={isHigh ? '#d1d5db' : '#4b5563'} />
                        </linearGradient>
                    </defs>
                    <circle
                        stroke="#121212"
                        fill="transparent"
                        strokeWidth={stroke}
                        r={normalizedRadius}
                        cx={radius}
                        cy={radius}
                        strokeLinecap="round"
                    />
                    <circle
                        stroke={`url(#${gradientId})`}
                        fill="transparent"
                        strokeWidth={stroke}
                        strokeDasharray={circumference + ' ' + circumference}
                        style={{ strokeDashoffset }}
                        strokeLinecap="round"
                        r={normalizedRadius}
                        cx={radius}
                        cy={radius}
                        className="transition-all duration-1000 ease-out"
                    />
                </svg>
                <div className="absolute flex flex-col items-center justify-center">
                    <span className="text-3xl font-bold text-white leading-none">{percentage}%</span>
                </div>
            </div>
            <span className={`text-[10px] font-bold tracking-widest uppercase ${isHigh ? 'text-white' : 'text-gray-400'}`}>
                {isHigh ? 'High Reliability' : 'Medium Reliability'}
            </span>
        </div>
    );
}

export function ProgressBar({ label, percentage, description, colorClass, icon }) {
    return (
        <div className="py-4 border-b border-white/[0.08] last:border-0">
            <div className="flex items-center justify-between mb-2">
                <div className="flex items-center text-gray-200">
                    <span className="mr-3 text-slate-400">{icon}</span>
                    <span className="text-sm font-semibold">{label}</span>
                </div>
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${colorClass}`}>
                    {percentage}%
                </span>
            </div>
            {description && <p className="text-[11px] text-slate-400 mb-2 leading-relaxed">{description}</p>}
        </div>
    );
}

// --- DASHBOARD PANELS COMPONENT ---
/**
 * BACKEND INTEGRATION:
 * The 'article' object passed here should contain the AI analysis data 
 * generated by your Python/LLM backend.
 * 
 * Expected properties:
 * - credibility_score: float (0.0 to 1.0)
 * - llm_analysis.claims: Array of strings
 */
export function DashboardPanels({ article, isGrid = false }) {
    const containerClasses = isGrid
        ? "flex flex-wrap gap-6 items-start"
        : "space-y-6";

    const itemClasses = isGrid
        ? "flex-grow flex-shrink-0 basis-full md:basis-[calc(50%-1.5rem)] lg:basis-[calc(33.333%-1.5rem)]"
        : "w-full";

    // ── Compute all 5 scores using LLM data first, then smart fallbacks ──
    const llm = article.llm_analysis || {};
    const cred = article.credibility_score; // 0-1 float, unique per article
    const risk = article.misinfo_risk_score; // 0-1 float, unique per article
    const claimsCount = Array.isArray(llm.claims) ? llm.claims.length : 0;
    const biasCount = Array.isArray(llm.bias_indicators) ? llm.bias_indicators.length : 0;
    const tone = llm.tone || '';

    // Tone to numeric mapping (used as a factor)
    const toneScoreMap = {
        neutral: 90, informative: 85, authoritative: 82,
        positive: 70, celebratory: 65, sympathetic: 60,
        critical: 40, negative: 35, urgent: 30,
        alarmist: 20, sarcastic: 25,
    };
    const toneNumeric = toneScoreMap[tone.toLowerCase()] || 55;

    // Helper: pick LLM score if present, otherwise compute from article-specific data
    const scores = {
        sourceCredibility: llm.source_credibility_score != null
            ? llm.source_credibility_score
            : (cred != null ? Math.round(cred * 100) : (risk != null ? Math.round((1 - risk) * 100) : 50)),

        factualAccuracy: llm.factual_accuracy_score != null
            ? llm.factual_accuracy_score
            : (cred != null
                ? Math.min(95, Math.max(10, Math.round(cred * 80 + claimsCount * 3)))
                : (risk != null ? Math.round((1 - risk) * 85) : 50)),

        objectivity: llm.objectivity_score != null
            ? llm.objectivity_score
            : (biasCount > 0
                ? Math.max(10, 92 - biasCount * 18)
                : (cred != null ? Math.min(95, Math.round(cred * 90 + 5)) : (risk != null ? Math.round((1 - risk) * 90) : 50))),

        toneFraming: llm.tone_framing_score != null
            ? llm.tone_framing_score
            : toneNumeric,

        biasDetection: llm.bias_score != null
            ? llm.bias_score
            : (biasCount > 0
                ? Math.max(8, 95 - biasCount * 22)
                : (cred != null ? Math.min(96, Math.round(cred * 95)) : (risk != null ? Math.round((1 - risk) * 92) : 50))),
    };

    return (
        <div className={containerClasses}>

            {/* Main AI Reliability Scorecard - ONLY for user posts */}
            {article.publisher_name === "User Submitted" && (
                <div className={`${itemClasses}`}>
                    <div className="glass-panel rounded-2xl p-6 h-full">
                        <h3 className="text-sm font-semibold text-gray-200 mb-4 border-b border-white/[0.08] pb-3">
                            Credibility Analysis
                        </h3>

                        <div className="text-center mb-2">
                            <h4 className="text-sm font-medium text-gray-300">AI Reliability Scorecard</h4>
                        </div>

                        <ScorecardCircle score={article.credibility_score} />

                        <div className="space-y-2 mt-4">
                            <ProgressBar
                                label="Source History"
                                percentage={scores.sourceCredibility}
                                description="Source history timeline based on past reporting accuracy."
                                colorClass={cred != null ? "bg-white/10 text-white" : "bg-gray-500/20 text-gray-400"}
                                icon={<span className="text-xl">⏱</span>}
                            />
                            <ProgressBar
                                label="Fact-Check Consistency"
                                percentage={scores.factualAccuracy}
                                description="Cross-referencing claims with verified databases."
                                colorClass={cred != null ? "bg-white/10 text-white" : "bg-gray-500/20 text-gray-400"}
                                icon={<span className="text-xl">✓</span>}
                            />
                            <ProgressBar
                                label="Bias Assessment"
                                percentage={scores.biasDetection}
                                description="Linguistic analysis of neutral framing and tone."
                                colorClass={cred != null ? "bg-white/10 text-white" : "bg-gray-500/20 text-gray-400"}
                                icon={<span className="text-xl">⚖</span>}
                            />
                        </div>
                    </div>
                </div>
            )}

            {/* Optional detailed claim panel for extra data from backend */}
            {article.llm_analysis?.claims?.length > 0 && (
                <div className={`${itemClasses}`}>
                    <div className="glass-panel rounded-2xl p-6 border-white/[0.08] bg-white/[0.02] h-full">
                        <h3 className="text-sm font-semibold text-white mb-4 uppercase tracking-wider flex items-center">
                            <span className="mr-2"></span> Technical Analysis
                        </h3>
                        <ul className="space-y-3">
                            {article.llm_analysis.claims.map((claim, idx) => (
                                <li key={idx} className="flex items-start text-[13px] text-gray-300">
                                    <span className="text-gray-400 mr-2 mt-0.5">•</span>
                                    {claim}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            )}

            {/* Cluster / Coverage Data — hidden if no cluster data */}
            {article.cluster_data && (
                <div className={`${itemClasses}`}>
                    <div className="glass-panel rounded-2xl p-6 border-white/[0.08] bg-white/[0.02] h-full">
                        <h3 className="text-sm font-semibold text-white mb-4 uppercase tracking-wider">Cross-Source Coverage Map</h3>
                        <div className="space-y-3">
                            {(article.cluster_data.coverage_map || []).slice(0, 5).map((source, idx) => (
                                <div key={idx} className="flex items-center justify-between p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] hover:bg-white/[0.05] transition-colors">
                                    <div className="flex items-center gap-3">
                                        <div className={`w-8 h-8 rounded-lg flex items-center justify-center text-xs font-bold ${source.is_original ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30' : 'bg-white/[0.05] text-gray-400 border border-white/[0.08]'}`}>
                                            {source.is_original ? '★' : (idx + 1)}
                                        </div>
                                        <div>
                                            <span className="text-sm font-medium text-gray-200 block">{source.publisher}</span>
                                            <span className="text-[10px] text-gray-500 uppercase tracking-wider">{source.is_original ? 'Original Source' : 'Coverage'}</span>
                                        </div>
                                    </div>
                                    <span className="text-xs font-bold text-gray-400">{Math.round(source.reputation * 100)}%</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}

            {/* AI Content Analysis Bars */}
            {(article.llm_analysis || cred != null) && (
                <div className={`${itemClasses}`}>
                    <div className="glass-panel rounded-2xl p-6 border-white/[0.08] bg-white/[0.02] h-full">
                        <h3 className="text-sm font-semibold text-white mb-2 uppercase tracking-wider flex items-center">
                            <span className="mr-2"></span> AI Content Analysis
                        </h3>
                        <p className="text-xs text-slate-400 mb-4">Deep linguistic and credibility audit across 5 dimensions</p>
                        <div className="w-full space-y-0">
                            <ProgressBar
                                label="Source Credibility"
                                percentage={scores.sourceCredibility}
                                description="Publisher track record, domain authority, and editorial standards."
                                colorClass="bg-emerald-500/20 text-emerald-400"
                                icon={<span className="text-xs">SRC</span>}
                            />
                            <ProgressBar
                                label="Factual Accuracy"
                                percentage={scores.factualAccuracy}
                                description="Cross-referencing key claims against verified databases and known facts."
                                colorClass="bg-cyan-500/20 text-cyan-400"
                                icon={<span className="text-xs">FCT</span>}
                            />
                            <ProgressBar
                                label="Objectivity"
                                percentage={scores.objectivity}
                                description="Measures neutral language use and absence of loaded or persuasive wording."
                                colorClass="bg-blue-500/20 text-blue-400"
                                icon={<span className="text-xs">OBJ</span>}
                            />
                            <ProgressBar
                                label="Tone & Framing"
                                percentage={scores.toneFraming}
                                description={`Detected tone: ${tone || 'unanalyzed'}. Evaluates emotional framing and narrative slant.`}
                                colorClass="bg-purple-500/20 text-purple-400"
                                icon={<span className="text-xs">TNF</span>}
                            />
                            <ProgressBar
                                label="Bias Detection"
                                percentage={scores.biasDetection}
                                description={biasCount > 0 ? `Flagged: ${llm.bias_indicators.slice(0, 2).join(', ')}` : 'No significant bias indicators detected in this article.'}
                                colorClass="bg-amber-500/20 text-amber-400"
                                icon={<span className="text-xs">BIA</span>}
                            />
                            <div className="flex items-center justify-center py-4 opacity-50 text-[10px] text-gray-500 uppercase tracking-widest border-t border-white/5 mt-2">
                                5-Factor Deep Analysis Complete
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
